"""init_db

Revision ID: c52787e572f5
Revises: c006e8463eb4
Create Date: 2025-08-12 11:56:05.100334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52787e572f5'
down_revision = 'c006e8463eb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
